### PR TITLE
added: smart-jump-find-references-with-rg

### PR DESCRIPTION
**Pull request by ncaq**
[BurntSushi/ripgrep: ripgrep recursively searches directories for a regex pattern](https://github.com/BurntSushi/ripgrep)
is some compatible to ag.
And faster than ag.

### CODE REVIEW

**Comment by ncaq** [comment]
Excuse me.
It was only part of what I thought would work ...
Let's fix it a little more.

**Comment by ncaq** [comment]
I fixed.

**Comment by jojojames** [comment]
Thanks! I don't know why the CI is erroring, don't yet have time to look into it. Will try to get to your PR soon!

**Comment by ncaq** [comment]
Since the CI error was also occurring in other pull requests, I decided that it was not relevant and opened this.
You don't have to rush to that because you have added this function to your environment.

**Comment by jojojames** [comment]
Sorry for the massive delay @ncaq . I kinda just forgot about this.

**Pull request merged**
