### PR TITLE
Add Dante for Haskell.

### PR DESCRIPTION
**Pull request by leungbk**

### CODE REVIEW

**Comment by jojojames** [comment]
Nice, thanks.

**Comment by jojojames** [comment]
@leungbk I just noticed dante has no jump-fn or refs-fn. Is this expected?

**Comment by leungbk** [comment]
@jojojames `dante` defines a `xref` backend, so it works with `xref`. Do I need to write a separate `jump-fn` and `refs-fn` in this case? It's been a while since I used `smart-jump`.

**Comment by jojojames** [comment]
Nah, I think you're good. Thanks for the quick reply.

**Pull request merged**
